'use client';
import Link from 'next/link';
import {useCart} from './CartProvider';
import {formatMoney} from '../lib/catalog';
import Dialog from './Dialog';
import ProductImage from './ProductImage';
export default function CartDrawer(){
 const {cart,demoLines,demo,open,setOpen,busy,notice,updateItem}=useCart();if(!open)return null;
 const lines=demo?demoLines.map(line=>({id:line.key,quantity:line.quantity,title:line.product.title,handle:line.product.handle,image:line.product.image,amount:line.product.price*line.quantity,currency:'INR'})):(cart?.lines?.nodes||[]).map(line=>({id:line.id,quantity:line.quantity,title:line.merchandise.product.title,handle:line.merchandise.product.handle,image:line.merchandise.image?.url,variant:line.merchandise.title==='Default Title'?'':line.merchandise.title,amount:Number(line.cost.totalAmount.amount),currency:line.cost.totalAmount.currencyCode}));
 const subtotal=demo?lines.reduce((sum,line)=>sum+line.amount,0):Number(cart?.cost?.subtotalAmount?.amount||0);
 return <Dialog title="Your bag" className="cart-dialog" onClose={()=>setOpen(false)}>{demo && <p className="cart-notice">You’re browsing a store preview. These sample pieces can’t be purchased yet.</p>}{notice && <p className="cart-notice" role="alert">{notice}</p>}{!lines.length && <div className="empty-cart"><h3 className="serif">Room for something new.</h3><p>Your bag is empty.</p><Link className="underlined-link" href="/products" onClick={()=>setOpen(false)}>EXPLORE AX →</Link></div>}<div className="cart-lines">{lines.map(line=><div className="cart-line" key={line.id}><Link className="cart-image" href={`/products/${line.handle}`} onClick={()=>setOpen(false)}><ProductImage src={line.image} alt={line.title} sizes="76px"/></Link><div><Link className="cart-line-title" href={`/products/${line.handle}`} onClick={()=>setOpen(false)}>{line.title}</Link>{line.variant && <p className="muted">{line.variant}</p>}<p>{formatMoney(line.amount,line.currency)}</p><div className="cart-line-bottom"><div className="quantity"><button aria-label={`Decrease ${line.title} quantity`} disabled={busy} onClick={()=>updateItem(line.id,line.quantity-1)}>−</button><span aria-live="polite">{line.quantity}</span><button aria-label={`Increase ${line.title} quantity`} disabled={busy||line.quantity>=99} onClick={()=>updateItem(line.id,line.quantity+1)}>+</button></div><button className="remove-item" disabled={busy} onClick={()=>updateItem(line.id,0)}>Remove</button></div></div></div>)}</div>{lines.length>0 && <><div className="cart-total"><span>Subtotal</span><strong>{formatMoney(subtotal,cart?.cost?.subtotalAmount?.currencyCode||'INR')}</strong></div>{demo?<button className="checkout-button" disabled>PREVIEW · CHECKOUT UNAVAILABLE</button>:busy?<button className="checkout-button" disabled>UPDATING BAG…</button>:<a className="checkout-button" href={cart.checkoutUrl}>CONTINUE TO CHECKOUT</a>}<p className="cart-note">Delivery options and charges are confirmed at checkout.</p></>}</Dialog>;
}
